build:
	# gcc -o test_stack.out test_stack.c;./test_stack.out;
	# gcc -o test_string_operations.out test_string_operations.c;./test_string_operations.out;
	rm test_expr.out;gcc -o test_expr.out test_expr.c;./test_expr.out;