build:
	# gcc -o test_stack.out test_stack.c;./test_stack.out;
	# gcc -o test_string_operations.out test_string_operations.c;./test_string_operations.out;
	rm test_parser_graph.out;gcc -o test_parser_graph.out test_parser_graph.c;./test_parser_graph.out;