Variable *A = createMatrix(2, 2);
Variable *InvA = createMatrix(2, 2);
Variable *detA = createScalar();
Variable *minusOne = createScalar();
Variable *NRTySFrzrmzlYGF = generateScalarFromNumber(2);
Variable *vEulQfpDBHlqDqr = generateScalarFromNumber(1);
Variable *lrfkQyuQFjKXyQV = substraction(NRTySFrzrmzlYGF, vEulQfpDBHlqDqr);
assign(minusOne, lrfkQyuQFjKXyQV);
assignToFlatten(A, 1, 0);assignToFlatten(A, 2, 1);assignToFlatten(A, 3, 2);assignToFlatten(A, 5, 3);
Variable *a = createScalar();
Variable *b = createScalar();
Variable *c = createScalar();
Variable *d = createScalar();
Variable *AITGDPHCSPIjtHb = generateScalarFromNumber(1);
Variable *sFyfvlADzPBfudk = generateScalarFromNumber(1);
Variable *rCRwDnXeuOQqekl = getDoubleIndex( A, AITGDPHCSPIjtHb, sFyfvlADzPBfudk );
assign(a, rCRwDnXeuOQqekl);
Variable *EffECLhbVFUkBye = generateScalarFromNumber(1);
Variable *qfQOJWTwosILEeZ = generateScalarFromNumber(2);
Variable *KlrwqAOzMiXrpif = getDoubleIndex( A, EffECLhbVFUkBye, qfQOJWTwosILEeZ );
assign(b, KlrwqAOzMiXrpif);
Variable *CQptkhHqrQdwfcA = generateScalarFromNumber(2);
Variable *YSSYoQcJomwUFBd = generateScalarFromNumber(1);
Variable *TxWJLkNgbqQmBxQ = getDoubleIndex( A, CQptkhHqrQdwfcA, YSSYoQcJomwUFBd );
assign(c, TxWJLkNgbqQmBxQ);
Variable *sYBlOetsWCRFHPX = generateScalarFromNumber(2);
Variable *PRbsshSjXDFileB = generateScalarFromNumber(2);
Variable *fXudZHiftaKCZVH = getDoubleIndex( A, sYBlOetsWCRFHPX, PRbsshSjXDFileB );
assign(d, fXudZHiftaKCZVH);
Variable *xwBCTOaYaxzFBjb = multiplication(a, d);
Variable *KRxIRImqPZWMSHl = multiplication(b, c);
Variable *PJhtAZhbuXhwaDL = substraction(xwBCTOaYaxzFBjb, KRxIRImqPZWMSHl);
assign(detA, PJhtAZhbuXhwaDL);
assignToDoubleIndex(InvA, 1, 1, d);
Variable *PTOyeziWkMGSovq = multiplication(minusOne, b);
assignToDoubleIndex(InvA, 1, 2, PTOyeziWkMGSovq);
Variable *zGDIxrPDdZpLcrW = multiplication(minusOne, c);
assignToDoubleIndex(InvA, 2, 1, zGDIxrPDdZpLcrW);
assignToDoubleIndex(InvA, 2, 2, a);
print(InvA);
printsep();
print(detA);
